# Generated by Django 4.0.4 on 2022-05-27 07:06

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1920, 1080], upload_to='news/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'webp'])])),
                ('image_uz', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1920, 1080], upload_to='news/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'webp'])])),
                ('image_ru', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1920, 1080], upload_to='news/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'webp'])])),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='news/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'gif'])])),
                ('video_title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('video_uz', models.FileField(blank=True, null=True, upload_to='news/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'gif'])])),
                ('video_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('video_ru', models.FileField(blank=True, null=True, upload_to='news/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'gif'])])),
                ('file_uz_one', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_two', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_three', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_four', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_five', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_six', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_seven', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_eight', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_nine', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_uz_ten', models.FileField(blank=True, null=True, upload_to='images/news/documents/uz', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_one', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_two', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_three', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_four', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_five', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_six', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_seven', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_eight', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_nine', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en_ten', models.FileField(blank=True, null=True, upload_to='images/news/documents/en', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_one', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_two', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_three', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_four', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_five', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_six', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_seven', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_eight', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_nine', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_ru_ten', models.FileField(blank=True, null=True, upload_to='images/news/documents/ru', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('extra_img_one', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1920, 1080], upload_to='images/news/extra', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])])),
                ('extra_img_two', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1920, 1080], upload_to='images/news/extra', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])])),
                ('extra_img_three', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1920, 1080], upload_to='images/news/extra', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])])),
                ('english', models.BooleanField(blank=True, default=1)),
                ('russian', models.BooleanField(blank=True, default=1)),
                ('uzbek', models.BooleanField(blank=True, default=1)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
